version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
    volumes:
      - inventory-db:/var/lib/mysql
volumes:
  inventory-db:
