export enum Listeners {
  CONNECTED="CONNECTED",
  DISCONNECTED="DISCONNECTED",
  HOST_LOGIN_SUCCESS="HOST_LOGIN_SUCCESS",
  HOST_LOGIN_ERROR="HOST_LOGIN_ERROR",
  HOST_CREATE_ROLE_ERROR="HOST_CREATE_ROLE_ERROR",
  HOST_CREATE_ITEM_ERROR="HOST_CREATE_ITEM_ERROR",
  HOST_UPDATE_ROLE_ERROR="HOST_UPDATE_ROLE_ERROR",
  HOST_UPDATE_ITEM_ERROR="HOST_UPDATE_ITEM_ERROR",
  HOST_ITEM_VISIBILITY_ERROR="HOST_ITEM_VISIBILITY_ERROR",
  HOST_USE_ITEM_ERROR="HOST_USE_ITEM_ERROR",
  GAME_UPDATE="GAME_UPDATE",
  ITEM_UPDATE="ITEM_UPDATE"
}

export const actionListeners = () => {
  let enumValues:Array<string> = [];

  for(let value in Listeners) {
    enumValues.push( value );
  }

  return enumValues;
}